name: e_commerce
description: A new Flutter project
publish_to: 'none/CoreFoundationKeys.html'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.1.0
  flutter_markdown: ^0.6.19
  uni_links: ^0.5.1
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.2.1
  flutter_phoenix: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - .env
  fonts:
    - family: LibreCaslonText
      fonts:
        - asset: assets/fonts/LibreCaslonText-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

  uses-material-design: true




