name: e_commerce
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^9.0.0
  go_router: ^16.0.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^6.0.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  pull_to_refresh_flutter3: ^2.0.2
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  app_links: ^6.4.0
  flutter_async_value: ^1.2.3
  google_sign_in: ^7.1.1
  toastification: ^3.0.2
  get_it: ^8.0.3
  flutter_markdown: ^0.7.5
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
#  adaptive_grid: ^1.0.3
#  json_annotation: ^4.9.0
#  fuzzy: ^0.5.1
#  http: ^1.4.0
#  flutter_hooks: ^0.21.2
#  cloudflare_turnstile: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.3
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0
  # TODO: change app name
  change_app_package_name: ^1.5.0
#  flutter_phoenix: ^1.0.0

flutter_gen:
  output: lib/core/constants/

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - dotenv
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400

  uses-material-design: true



