name: e_commerce
description: A new Flutter project
publish_to: 'none/CoreFoundationKeys.html'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  flutter_bloc: ^9.0.0
  flutter_markdown: ^0.7.5
  go_router: ^14.7.2
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.2.1
  convex_bottom_bar: ^3.2.0
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  pull_to_refresh_flutter3: ^2.0.2
  persistent_bottom_nav_bar: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
#  carousel_slider: ^5.0.0
#  flutter_staggered_grid_view: ^0.7.0
#  cloudflare_turnstile: ^3.2.1
#  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#  flutter_phoenix: ^1.0.0

flutter:
  generate: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: LibreCaslonText
      fonts:
        - asset: assets/fonts/LibreCaslonText-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

  uses-material-design: true



